#
# Voyage Config v${version}
#

# Will log debug information to the console. Meant for developers or bug hunters.
enable_debug: true

# If true, Voyage will take control of handling worlds.
handle_worlds: true