name: Voyage
version: '${version}'
main: me.itsmcb.voyage.Voyage
api-version: 1.18
load: STARTUP
authors: [ ItsMCB ]
description: Modern Minecraft world management solution
website: https://github.com/ItsMCB/Voyage
commands:
  voyage:
      description: Main voyage command
  world:
    description: Configure worlds